query GET_PRODUCT($sku: ID!){
  product(identifier: {field: sku, value: $sku}){
    productId
    productName
  }
}

# product(
# slug: String
# identifier: ProductUniqueIdentifier
# regionId: String
# salesChannel: Int
# ): Product
