#* the purpose of this query is to verify if the product exists in the first place
query GET_PRODUCT($sku: ID!){
  product(identifier: {field: sku, value: $sku}) {
    productName
    productId
  }
}

# product(
# slug: String
# identifier: ProductUniqueIdentifier
# regionId: String
# salesChannel: Int
# ): Product
